<?php

/**
 * ContestVoterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContestVoterTable extends RecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContestVoterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContestVoter');
    }
}