<?php

/**
 * EventParticipantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventParticipantTable extends RecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventParticipantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventParticipant');
    }
}