<?php

/**
 * PollOption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    InfiniteCMS
 * @subpackage Models
 * @author     Nami-D0C <nami.d0c.0@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PollOption extends BasePollOption
{
	public function getPercent()
	{
		if ($this->Poll->countPolleds() == 0)
			return 0;
		return ($this->Polleds->count() / $this->Poll->countPolleds()) * 100;
	}
	public function getVoteLink()
	{
		return make_link(array('controller' => 'PollOption', 'action' => 'vote', 'id' => $this->id), lang('vote'));
	}
	public function getDeleteLink()
	{
		return make_link(array('controller' => __CLASS__, 'action' => 'delete', 'id' => $this->id), lang('act.delete'));
	}
}