<?php

/**
 * PrivateMessageAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrivateMessageAnswerTable extends RecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrivateMessageAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PrivateMessageAnswer');
    }
}