<?php

/**
 * PrivateMessageThreadReceiverTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrivateMessageThreadReceiverTable extends RecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrivateMessageThreadReceiverTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PrivateMessageThreadReceiver');
    }
}