<?php

/**
 * PrivateMessageThreadReceiver
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    InfiniteCMS
 * @subpackage Models
 * @author     Vendethiel <vendethiel@hotmail.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PrivateMessageThreadReceiver extends BasePrivateMessageThreadReceiver
{
	public function getLink()
	{
		if ($this->present)
			return make_link($this->Account);
		else
			return make_link($this->Account, tag('strike', array('title' => lang('has_left')), $this->Account->getName()));
	}
}