<?php

/**
 * ShopCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    InfiniteCMS
 * @subpackage Models
 * @author     Vendethiel <vendethiel@hotmail.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ShopCategory extends BaseShopCategory
{
	public function getName()
	{
		return lang($this->name, NULL, '%%key%%');
	}
	public function getRawName()
	{
		return $this->_get('name');
	}

	public function getUpdateLink()
	{
		return make_link(array('controller' => __CLASS__, 'action' => 'update', 'id' => $this->id), lang('act._edit'));
	}
	public function getDeleteLink()
	{
		return make_link(array('controller' => __CLASS__, 'action' => 'delete', 'id' => $this->id), lang('act.delete'));
	}
}