CREATE TABLE `accounts` (`guid` INT AUTO_INCREMENT, `account` VARCHAR(30), `pass` VARCHAR(50), `level` INT DEFAULT '0', `email` VARCHAR(100), `lastip` VARCHAR(15), `lastconnectiondate` VARCHAR(100), `question` VARCHAR(100) DEFAULT 'DELETE?', `reponse` VARCHAR(100) DEFAULT 'DELETE', `pseudo` VARCHAR(30), `banned` bool, `reload_needed` bool, `bankkamas` INT DEFAULT '0', `bank` TEXT, `friends` TEXT, `logged` TINYINT(1) DEFAULT '0', `vip` TINYINT(1) DEFAULT '0', PRIMARY KEY(`guid`)) ENGINE = INNODB;
CREATE TABLE `personnages` (`guid` INT, `name` VARCHAR(30), `sexe` TINYINT, `class` SMALLINT, `color1` INT, `color2` INT, `color3` INT, `kamas` INT, `spellboost` INT, `capital` INT, `energy` INT DEFAULT '10000', `level` INT, `xp` BIGINT DEFAULT '0', `size` INT, `gfx` INT, `alignement` INT DEFAULT '0', `honor` INT DEFAULT '0', `deshonor` INT DEFAULT '0', `alvl` INT DEFAULT '1', `account` INT, `vitalite` INT, `force` INT DEFAULT '0', `sagesse` INT DEFAULT '0', `intelligence` INT DEFAULT '0', `chance` INT DEFAULT '0', `agilite` INT DEFAULT '0', `seespell` TINYINT DEFAULT '0', `seefriend` TINYINT DEFAULT '1', `canaux` VARCHAR(15) DEFAULT '*#%!pi$:?', `map` INT DEFAULT '8479', `cell` INT, `pdvper` INT DEFAULT '100', `spells` TEXT, `objets` TEXT, `savepos` VARCHAR(20) DEFAULT '10298,314', `zaaps` VARCHAR(250) DEFAULT NULL, `jobs` TEXT, `mountxpgive` INT DEFAULT '0', `mount` INT DEFAULT '-1', INDEX `account_idx` (`account`), INDEX `mount_idx` (`mount`), PRIMARY KEY(`guid`)) ENGINE = INNODB;
CREATE TABLE `comment` (`id` BIGINT AUTO_INCREMENT, `news_id` BIGINT, `author_id` BIGINT, `title` VARCHAR(255), `content` text, `created_at` DATETIME NOT NULL, INDEX `news_id_idx` (`news_id`), INDEX `author_id_idx` (`author_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `contest` (`id` BIGINT AUTO_INCREMENT, `reward_id` INT, `name` TEXT, `ended` INT DEFAULT 0, `level` INT, INDEX `reward_id_idx` (`reward_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `contest_juror` (`id` BIGINT AUTO_INCREMENT, `contest_id` INT, `user_id` INT, INDEX `contest_id_idx` (`contest_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `contest_participant` (`id` BIGINT AUTO_INCREMENT, `contest_id` INT, `character_id` INT, `votes` BIGINT DEFAULT 0, `position` BIGINT DEFAULT 0, INDEX `contest_id_idx` (`contest_id`), INDEX `character_id_idx` (`character_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `contest_voter` (`id` BIGINT AUTO_INCREMENT, `contest_id` INT, `user_id` INT, INDEX `contest_id_idx` (`contest_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `event` (`id` BIGINT AUTO_INCREMENT, `guild_id` BIGINT, `winner_id` BIGINT, `reward_id` BIGINT, `is_tombola` bool, `name` VARCHAR(255), `period` datetime, `capacity` BIGINT DEFAULT -1, INDEX `guild_id_idx` (`guild_id`), INDEX `winner_id_idx` (`winner_id`), INDEX `reward_id_idx` (`reward_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `event_participant` (`id` BIGINT AUTO_INCREMENT, `event_id` INT, `character_id` INT, INDEX `character_id_idx` (`character_id`), INDEX `event_id_idx` (`event_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `guilds` (`id` INT, `name` VARCHAR(50), `emblem` VARCHAR(20), `lvl` INT DEFAULT '1', `xp` BIGINT DEFAULT '0') ENGINE = INNODB;
CREATE TABLE `guild_members` (`guid` INT, `guild` INT, `rank` INT, `rights` INT, `xpdone` BIGINT, `pxp` INT, INDEX `guild_idx` (`guild`), PRIMARY KEY(`guid`)) ENGINE = INNODB;
CREATE TABLE `items` (`guid` INT, `template` INT, `qua` INT, `pos` INT, `stats` TEXT, PRIMARY KEY(`guid`)) ENGINE = INNODB;
CREATE TABLE `live_action` (`id` INT AUTO_INCREMENT, `playerid` INT, `action` INT, `nombre` INT, INDEX `playerid_idx` (`playerid`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `mounts_data` (`id` INT, `color` INT, `sexe` INT, `name` VARCHAR(30), `xp` INT, `level` INT, `endurance` INT, `amour` INT, `maturite` INT, `serenite` INT, `reproductions` INT, `fatigue` INT, `energie` INT, `items` TEXT, `ancetres` VARCHAR(50) DEFAULT ',,,,,,,,,,,,,', PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `mountpark_data` (`mapid` INT, `size` INT, `owner` INT, `guild` INT DEFAULT '-1', `price` INT DEFAULT '0', `data` TEXT, PRIMARY KEY(`mapid`)) ENGINE = INNODB;
CREATE TABLE `news` (`id` BIGINT AUTO_INCREMENT, `author_id` BIGINT, `title` VARCHAR(255), `content` text, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, INDEX `author_id_idx` (`author_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `poll` (`id` BIGINT AUTO_INCREMENT, `name` VARCHAR(255), `date_start` DATE, `date_end` DATE, PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `poll_option` (`id` BIGINT AUTO_INCREMENT, `poll_id` BIGINT, `name` VARCHAR(255), INDEX `poll_id_idx` (`poll_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `poll_option_user` (`id` BIGINT AUTO_INCREMENT, `poll_option_id` BIGINT, `account_id` BIGINT, INDEX `account_id_idx` (`account_id`), INDEX `poll_option_id_idx` (`poll_option_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `private_message_answer` (`id` BIGINT AUTO_INCREMENT, `thread_id` INT, `author_id` INT, `message` text, `created_at` DATETIME NOT NULL, INDEX `thread_id_idx` (`thread_id`), INDEX `author_id_idx` (`author_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `private_message_thread` (`id` BIGINT AUTO_INCREMENT, `title` VARCHAR(255), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `private_message_thread_receiver` (`id` BIGINT AUTO_INCREMENT, `thread_id` INT, `account_id` INT, `present` bool DEFAULT 1, `next_page` INT DEFAULT 1, INDEX `thread_id_idx` (`thread_id`), INDEX `account_id_idx` (`account_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `review` (`id` BIGINT AUTO_INCREMENT, `author_id` BIGINT, `comment` text, `created_at` DATETIME NOT NULL, INDEX `author_id_idx` (`author_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `shop_category` (`id` BIGINT AUTO_INCREMENT, `name` VARCHAR(255), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `shop_item` (`id` BIGINT AUTO_INCREMENT, `category_id` BIGINT, `name` VARCHAR(255), `cost` BIGINT, `cost_vip` BIGINT, `description` text, `is_vip` TINYINT(1) DEFAULT '0', `is_lottery` TINYINT(1) DEFAULT '0', `is_hidden` TINYINT(1) DEFAULT '0', INDEX `category_id_idx` (`category_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `shop_item_effect` (`id` BIGINT AUTO_INCREMENT, `item_id` BIGINT, `type` BIGINT, `value` VARCHAR(255), INDEX `item_id_idx` (`item_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `staff_role` (`id` BIGINT AUTO_INCREMENT, `account_id` BIGINT, `name` VARCHAR(255), INDEX `account_id_idx` (`account_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `ticket` (`id` BIGINT AUTO_INCREMENT, `category_id` BIGINT, `state` VARCHAR(255), `name` VARCHAR(255), INDEX `category_id_idx` (`category_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `ticket_answer` (`id` BIGINT AUTO_INCREMENT, `ticket_id` BIGINT, `author_id` BIGINT, `content` text, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, INDEX `ticket_id_idx` (`ticket_id`), INDEX `author_id_idx` (`author_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `ticket_category` (`id` BIGINT AUTO_INCREMENT, `name` VARCHAR(255), `icon` VARCHAR(40), `description` text, `root_id` BIGINT, `lft` INT, `rgt` INT, `level` SMALLINT, PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE `user` (`id` BIGINT AUTO_INCREMENT, `guid` BIGINT, `lastvote` BIGINT, `points` BIGINT DEFAULT 0, `audiotel` BIGINT DEFAULT 0, `votes` BIGINT DEFAULT 0, `lastip` BIGINT, `culture` VARCHAR(255), `main_char` BIGINT, INDEX `guid_idx` (`guid`), PRIMARY KEY(`id`)) ENGINE = INNODB;
ALTER TABLE `personnages` ADD CONSTRAINT `personnages_mount_mounts_data_id` FOREIGN KEY (`mount`) REFERENCES `mounts_data`(`id`);
ALTER TABLE `personnages` ADD CONSTRAINT `personnages_account_accounts_guid` FOREIGN KEY (`account`) REFERENCES `accounts`(`guid`);
ALTER TABLE `comment` ADD CONSTRAINT `comment_news_id_news_id` FOREIGN KEY (`news_id`) REFERENCES `news`(`id`);
ALTER TABLE `comment` ADD CONSTRAINT `comment_author_id_user_id` FOREIGN KEY (`author_id`) REFERENCES `user`(`id`);
ALTER TABLE `contest` ADD CONSTRAINT `contest_reward_id_shop_item_id` FOREIGN KEY (`reward_id`) REFERENCES `shop_item`(`id`);
ALTER TABLE `contest_juror` ADD CONSTRAINT `contest_juror_contest_id_contest_id` FOREIGN KEY (`contest_id`) REFERENCES `contest`(`id`);
ALTER TABLE `contest_participant` ADD CONSTRAINT `contest_participant_contest_id_contest_id` FOREIGN KEY (`contest_id`) REFERENCES `contest`(`id`);
ALTER TABLE `contest_participant` ADD CONSTRAINT `contest_participant_character_id_personnages_guid` FOREIGN KEY (`character_id`) REFERENCES `personnages`(`guid`);
ALTER TABLE `contest_voter` ADD CONSTRAINT `contest_voter_contest_id_contest_id` FOREIGN KEY (`contest_id`) REFERENCES `contest`(`id`);
ALTER TABLE `event` ADD CONSTRAINT `event_winner_id_personnages_guid` FOREIGN KEY (`winner_id`) REFERENCES `personnages`(`guid`);
ALTER TABLE `event` ADD CONSTRAINT `event_reward_id_shop_item_id` FOREIGN KEY (`reward_id`) REFERENCES `shop_item`(`id`);
ALTER TABLE `event` ADD CONSTRAINT `event_guild_id_guilds_id` FOREIGN KEY (`guild_id`) REFERENCES `guilds`(`id`);
ALTER TABLE `event_participant` ADD CONSTRAINT `event_participant_event_id_event_id` FOREIGN KEY (`event_id`) REFERENCES `event`(`id`);
ALTER TABLE `event_participant` ADD CONSTRAINT `event_participant_character_id_personnages_guid` FOREIGN KEY (`character_id`) REFERENCES `personnages`(`guid`);
ALTER TABLE `guild_members` ADD CONSTRAINT `guild_members_guild_guilds_id` FOREIGN KEY (`guild`) REFERENCES `guilds`(`id`);
ALTER TABLE `live_action` ADD CONSTRAINT `live_action_playerid_personnages_guid` FOREIGN KEY (`playerid`) REFERENCES `personnages`(`guid`);
ALTER TABLE `news` ADD CONSTRAINT `news_author_id_user_id` FOREIGN KEY (`author_id`) REFERENCES `user`(`id`);
ALTER TABLE `poll_option` ADD CONSTRAINT `poll_option_poll_id_poll_id` FOREIGN KEY (`poll_id`) REFERENCES `poll`(`id`);
ALTER TABLE `poll_option_user` ADD CONSTRAINT `poll_option_user_poll_option_id_poll_option_id` FOREIGN KEY (`poll_option_id`) REFERENCES `poll_option`(`id`);
ALTER TABLE `poll_option_user` ADD CONSTRAINT `poll_option_user_account_id_user_id` FOREIGN KEY (`account_id`) REFERENCES `user`(`id`);
ALTER TABLE `private_message_answer` ADD CONSTRAINT `private_message_answer_thread_id_private_message_thread_id` FOREIGN KEY (`thread_id`) REFERENCES `private_message_thread`(`id`);
ALTER TABLE `private_message_answer` ADD CONSTRAINT `private_message_answer_author_id_user_guid` FOREIGN KEY (`author_id`) REFERENCES `user`(`guid`);
ALTER TABLE `private_message_thread_receiver` ADD CONSTRAINT `ptpi` FOREIGN KEY (`thread_id`) REFERENCES `private_message_thread`(`id`);
ALTER TABLE `private_message_thread_receiver` ADD CONSTRAINT `private_message_thread_receiver_account_id_user_guid` FOREIGN KEY (`account_id`) REFERENCES `user`(`guid`);
ALTER TABLE `private_message_thread_receiver` ADD CONSTRAINT `private_message_thread_receiver_account_id_accounts_guid` FOREIGN KEY (`account_id`) REFERENCES `accounts`(`guid`);
ALTER TABLE `review` ADD CONSTRAINT `review_author_id_user_id` FOREIGN KEY (`author_id`) REFERENCES `user`(`id`);
ALTER TABLE `shop_item` ADD CONSTRAINT `shop_item_category_id_shop_category_id` FOREIGN KEY (`category_id`) REFERENCES `shop_category`(`id`);
ALTER TABLE `shop_item_effect` ADD CONSTRAINT `shop_item_effect_item_id_shop_item_id` FOREIGN KEY (`item_id`) REFERENCES `shop_item`(`id`);
ALTER TABLE `staff_role` ADD CONSTRAINT `staff_role_account_id_accounts_guid` FOREIGN KEY (`account_id`) REFERENCES `accounts`(`guid`);
ALTER TABLE `ticket` ADD CONSTRAINT `ticket_category_id_ticket_category_id` FOREIGN KEY (`category_id`) REFERENCES `ticket_category`(`id`);
ALTER TABLE `ticket_answer` ADD CONSTRAINT `ticket_answer_ticket_id_ticket_id` FOREIGN KEY (`ticket_id`) REFERENCES `ticket`(`id`);
ALTER TABLE `ticket_answer` ADD CONSTRAINT `ticket_answer_author_id_user_id` FOREIGN KEY (`author_id`) REFERENCES `user`(`id`);
ALTER TABLE `user` ADD CONSTRAINT `user_guid_accounts_guid` FOREIGN KEY (`guid`) REFERENCES `accounts`(`guid`);
