<?php

/**
 * DropTable
 * 
 * This class has been auto-generated by Nami-Doc's Doctrine:Table Classes Generator
 * 
 * @package    InfiniteCMS
 * @subpackage Models
 * @author     Nami-Doc <nami.d0c.0@gmail.com>
 * @version    SVN: $Id: DropsTable.php 20 2010-09-24 08:51:22Z nami.d0c.0 $
 */
class DropTable extends RecordTable
{
}