<?php

/**
 * Drop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Drops.php 20 2010-09-24 08:51:22Z nami.d0c.0 $
 */
class Drop extends BaseDrop
{

}