<?php

/**
 * Contest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    InfiniteCMS
 * @subpackage Models
 * @author     Vendethiel <vendethiel@hotmail.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Contest extends BaseContest
{
	public function getURL()
	{
		return array('controller' => 'Character', 'action' => 'ladder', 'contest' => $this->id);
	}
	public function getParticipateLink()
	{
		return make_link(array('controller' => 'ContestParticipant', 'action' => 'update', 'id' => $this->id), lang('contest.compete'));
	}
	public function getEndLink()
	{
		return make_link(array('controller' => 'Contest', 'action' => 'end', 'id' => $this->id), lang('contest.end'));
	}

	public function getName()
	{
		return lang($this->_get('name'), NULL, '%%key%%');
	}
}