<?php

/**
 * Event
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    InfiniteCMS
 * @subpackage Models
 * @author     Vendethiel <vendethiel@hotmail.fr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Event extends BaseEvent
{
	protected $elapsed = null;

	public function isElapsed()
	{
		if (null === $this->elapsed)
		{
			list($date, $time) = explode(' ', $this->period);
			list($y, $mo, $d) = explode('-', $date);
			list($h, $mi, $s) = explode(':', $time);

			$this->elapsed = date_passed(mktime($h, $mi, $s, $mo, $d, $y));
		}
		return $this->elapsed;
	}
	public function refreshElapsed()
	{
		$this->elapsed = null;
	}
}