<?php

/**
 * PrivateMessageThreadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrivateMessageThreadTable extends RecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrivateMessageThreadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PrivateMessageThread');
    }
}