<?php

/**
 * ShopCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopCategoryTable extends RecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopCategory');
    }
}